### ISSUE TITLE
Phase5-4 Checkout fails 

### ISSUE THREAD

**Issue by s1155031145** [ierg4210/shop34#2]
Issue: Two items were brought and I was directed to the login page. After logging in, it failed to bring me to the paypal checkout page. 

Proof: http://postimg.org/image/450i6uvsj/

**Comment by s1155034160** [comment]
Can you be more precise on how to generate the problem? May be it is your connection problem.

**Comment by diaowenrui** [comment]
[TA comment] Can not repeat this problem.
